window.SLIT_LAMP_PARTS=[
["Binocular Eyepieces (Oculars)","Provide the binocular, magnified view through the microscope.","Adjust the interpupillary distance until both views merge into one circle. Set each ocular for your refractive correction before beginning.","A clear binocular image improves stereopsis and depth judgment.","Beginning before merging the ocular images or correcting the eyepieces."],
["Magnification Changer (Drum)","Changes microscope magnification while maintaining the viewing axis.","Begin at low magnification. Increase power after the target is centered and focused.","Low power gives context; high power is best for fine detail.","Starting at high magnification and losing orientation."],
["Brightness Control (Rheostat)","Controls the intensity of the illumination beam.","Start dim and increase only until the target is clearly visible.","The lowest useful illumination improves comfort and reduces tearing.","Using maximum brightness throughout the examination."],
["Filter Selector","Places the selected filter into the illumination pathway.","Use cobalt blue after fluorescein, red-free to increase contrast, or neutral density to reduce intensity.","Confirm the filter before interpreting color or fluorescein staining.","Selecting a filter without understanding its visual effect."],
["LED Light Source / Illumination Tower","Generates and directs the slit lamp illumination beam.","Turn on the unit, then use the controls below the tower to shape and position the beam.","If the view is dark, check the source and beam position before changing focus.","Confusing an off-center beam with a focusing problem."],
["Forehead Rest","Stabilizes the forehead and limits forward or backward movement.","Ask the patient to keep the forehead firmly against the band.","A patient who repeatedly drifts out of focus may have lost forehead contact.","Refocusing without first checking patient position."],
["Canthus Alignment Marker","References the correct vertical height for the patient’s eye.","Raise or lower the chin rest until the lateral canthus aligns with the marker.","Correct alignment keeps the microscope within comfortable vertical travel.","Compensating for poor patient height with the joystick."],
["Chin Rest","Supports the patient’s chin and stabilizes the head.","Ask the patient to place the chin fully inside the cup while maintaining forehead contact.","Stable chin and forehead contact make fine focus easier.","Allowing the chin to rest on the edge or support."],
["Goldmann Applanation Tonometer","Measures intraocular pressure by applanating a standardized corneal area.","After anesthetic and fluorescein, swing the prism into position, align the mires under cobalt blue light, and adjust until their inner edges meet.","Excess fluorescein makes thick mires and may overestimate pressure.","Pressing on the globe or lids while holding the eye open."],
["Beam Height Control","Adjusts the vertical height of the slit beam.","Turn the lower illumination control to shorten or lengthen the beam.","A short beam isolates a small area and reduces glare.","Using an unnecessarily tall beam."],
["Handle Bar","Provides a stable handhold for moving or positioning the instrument table.","Use the handle bar to guide the table carefully when repositioning the unit.","Use the handle—not the slit lamp optics or illumination tower—when moving the table.","Pulling or pushing on delicate slit lamp components instead of the handle bar."],
["Base Lock","Locks or releases movement of the slit-lamp base.","Release before coarse positioning; secure when the instrument must remain stationary.","If the base will not move, check the lock first.","Forcing the base while it is locked."],
["Joystick","Moves the slit lamp in four directions; rotation raises or lowers the microscope.","Keep one hand on the joystick. Use small movements to center and focus; rotate for vertical adjustment.","Most focusing is performed by moving the microscope, not changing the eyepieces.","Moving the patient’s head instead of the instrument."],
["Illumination Arm","Changes the angle between illumination and observation.","Swing the arm to create direct, oblique, retroillumination, and sclerotic-scatter views.","Changing the angle often reveals findings hidden in straight-on light.","Leaving the arm at one angle for the entire examination."]
].map((p,i)=>({id:i+1,name:p[0],function:p[1],use:p[2],pearl:p[3],mistake:p[4]}));
